#!/bin/bash

# Version 1.1.3
# Date: Jan. 26th, 2014
# Author: Li, Xiang

# This script is to help us remove the weakest sources automatically
# An auxiliary tool to help ScienceTools

#=====================================================================
# Variables to be defined by yourself

# result file generated by gtlike
result=results.dat

# sources whose TS < ts_limit will be removed
ts_limit=1.0

# the model file, with which gtlike runs, or the one gtlike generates
model=model.xml

# output model file, in which low TS sources have been removed
model_rmweak=model_rmweak.xml
#=====================================================================

model_tmp=model_tmp.xml
rmlist=rmlist.dat
rmlist_tmp=rmlist_tmp.dat

cp $model $model_rmweak

sed '1!G;h;$!d' $result | grep TS -A 6 | sed '/^[^{T]*$/d' | awk -F "'" -v limit="$ts_limit" '/^'\''TS/{ts=$4;next}{if(ts<limit){print $2;ts=limit+1}}' > $rmlist

echo 'removed sources:'
cat $rmlist

# To convert '+' to '\\+' in order to avoid the conflict with regular expression
sed 's/\+/\\\\\+/g' $rmlist > $rmlist_tmp
mv $rmlist_tmp $rmlist

while read srcname;
do
	cp $model_rmweak $model_tmp
	awk 'BEGIN{tag=0} /^.*'$srcname'/{tag=1}{if(tag==0){print}}/^.*<\/source>$/{tag=0}' $model_tmp > $model_rmweak
done < $rmlist

echo "`cat $rmlist | wc -l` weakest sources(TS < $ts_limit) are removed from model file"

rm -f $model_tmp $rmlist


#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Updating catalog:

# V1.1.3
# Use sed command to eliminate the incompatiblity between Linux-Bash and Macintosh-Bash

# V1.1.2
# Add two characters to work on the output model file by gtlike as well

# V1.1.1
# A small change to make it more compatible

# V1.1.0
# Taking account of the symbol '+' in the name of some in Fermi LAT Point Source Catalog

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
